/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarPart: typeof import('./src/components/home/left/BarPart.vue')['default']
    BottomFunctionGroup: typeof import('./src/components/home/left/BottomFunctionGroup.vue')['default']
    BottomGroup: typeof import('./src/components/home/left/BottomGroup.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    Left: typeof import('./src/components/home/Left.vue')['default']
    LeftSidebar: typeof import('./src/components/home/LeftSidebar.vue')['default']
    LogoPart: typeof import('./src/components/home/left/LogoPart.vue')['default']
    PaperInfo: typeof import('./src/components/home/right/PaperInfo.vue')['default']
    Right: typeof import('./src/components/home/Right.vue')['default']
    RightSidebar: typeof import('./src/components/home/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAndUpload: typeof import('./src/components/home/right/paper-info/SearchAndUpload.vue')['default']
    ShowInfo: typeof import('./src/components/home/right/paper-info/ShowInfo.vue')['default']
    ShowPage: typeof import('./src/components/home/right/paper-info/show-info/ShowPage.vue')['default']
    ShowTable: typeof import('./src/components/home/right/paper-info/show-info/ShowTable.vue')['default']
    TreeRightMenu: typeof import('./src/components/home/left/tree/TreeRightMenu.vue')['default']
  }
}
